# Generated by Django 4.2.11 on 2024-04-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(max_length=255, upload_to='product/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='last_update',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
